//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockServiceLibrary
{
    
    
    /// <summary>
    /// The ServiceConfigurationSection Configuration Section.
    /// </summary>
    public partial class ServiceConfigurationSection : global::System.Configuration.ConfigurationSection
    {
        
        #region Singleton Instance
        /// <summary>
        /// The XML name of the ServiceConfigurationSection Configuration Section.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        internal const string ServiceConfigurationSectionSectionName = "serviceConfigurationSection";
        
        /// <summary>
        /// The XML path of the ServiceConfigurationSection Configuration Section.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        internal const string ServiceConfigurationSectionSectionPath = "serviceConfigurationSection";
        
        /// <summary>
        /// Gets the ServiceConfigurationSection instance.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        public static global::StockServiceLibrary.ServiceConfigurationSection Instance
        {
            get
            {
                return ((global::StockServiceLibrary.ServiceConfigurationSection)(global::System.Configuration.ConfigurationManager.GetSection(global::StockServiceLibrary.ServiceConfigurationSection.ServiceConfigurationSectionSectionPath)));
            }
        }
        #endregion
        
        #region Xmlns Property
        /// <summary>
        /// The XML name of the <see cref="Xmlns"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        internal const string XmlnsPropertyName = "xmlns";
        
        /// <summary>
        /// Gets the XML namespace of this Configuration Section.
        /// </summary>
        /// <remarks>
        /// This property makes sure that if the configuration file contains the XML namespace,
        /// the parser doesn't throw an exception because it encounters the unknown "xmlns" attribute.
        /// </remarks>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::StockServiceLibrary.ServiceConfigurationSection.XmlnsPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public string Xmlns
        {
            get
            {
                return ((string)(base[global::StockServiceLibrary.ServiceConfigurationSection.XmlnsPropertyName]));
            }
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region RabbitMQ_HostName Property
        /// <summary>
        /// The XML name of the <see cref="RabbitMQ_HostName"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        internal const string RabbitMQ_HostNamePropertyName = "rabbitMQ_HostName";
        
        /// <summary>
        /// Gets or sets the RabbitMQ_HostName.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        [global::System.ComponentModel.DescriptionAttribute("The RabbitMQ_HostName.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::StockServiceLibrary.ServiceConfigurationSection.RabbitMQ_HostNamePropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual string RabbitMQ_HostName
        {
            get
            {
                return ((string)(base[global::StockServiceLibrary.ServiceConfigurationSection.RabbitMQ_HostNamePropertyName]));
            }
            set
            {
                base[global::StockServiceLibrary.ServiceConfigurationSection.RabbitMQ_HostNamePropertyName] = value;
            }
        }
        #endregion
    }
}
